### ISSUE TITLE
ValueError: No checkpoint file found in: None

### ISSUE THREAD

**Issue by IvyGongoogle** [KranthiGV/Pretrained-Show-and-Tell-model#3] opened 2017-05-27 13:40 UTC
hello, I download the pre-trained model you provide and put it in the same location as model.ckpt-2000000.index or  model.ckpt-1000000.index. but when I run 
```
bazel-bin/im2txt/run_inference \
  --checkpoint_path=${CHECKPOINT_PATH} \
  --vocab_file=${VOCAB_FILE} \
  --input_files=${IMAGE_FILE}
```
it shows error:
```
NFO:tensorflow:Building model.
Traceback (most recent call last):
  File "/home/ztgong/work/deeplearning-tools/tensorflow/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 85, in <module>
    tf.app.run()
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ztgong/work/deeplearning-tools/tensorflow/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 51, in main
    FLAGS.checkpoint_path)
  File "/home/ztgong/work/deeplearning-tools/tensorflow/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/inference_wrapper_base.py", line 118, in build_graph_from_config
    return self._create_restore_fn(checkpoint_path, saver)
  File "/home/ztgong/work/deeplearning-tools/tensorflow/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/inference_wrapper_base.py", line 92, in _create_restore_fn
    raise ValueError("No checkpoint file found in: %s" % checkpoint_path)
ValueError: No checkpoint file found in: None
```
what went wrong? can you provide some advises?

**Comment by IvyGongoogle** [comment] 2017-05-27 14:01
I have solved it. see [](https://github.com/tensorflow/models/issues/466)

**Comment by KranthiGV** [comment] 2017-05-27 17:39
Maybe the issue is that you didn't set CHECKPOINT_PATH and VOCAB_FILE correctly.
Please let us know what it was. :)

**Comment by IvyGongoogle** [comment] 2017-05-28 02:36
@KranthiGV yes,but I have solved it through [issue](https://github.com/tensorflow/models/issues/466)

**Comment by KranthiGV** [comment] 2017-05-28 06:17
Okay. Closing it.

**Closed by KranthiGV** 2017-05-28 06:17 UTC
